export const SET_BUILDING_COORDINATES = 'COORDINATES/GET_BUILDING_COORDINATES'
export const ADD_BUILDING_INFO = 'BUILDING/ADD_BUILDING_INFO'
export const UPDATE_BUILDING_INFO = 'BUILDING/UPDATE_BUILDING_INFO'
export const REMOVE_BUILDING_INFO = 'BUILDING/REMOVE_BUILDING_INFO'